package com.portal.repository;

import java.util.Date;
import java.util.List;

import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.transaction.annotation.Transactional;

import com.portal.clf.entities.ClfOrderItems;

public interface ClfOrderItemsRepo extends CrudRepository<ClfOrderItems, String>{

	@Query("from ClfOrderItems us where clfOrders.orderId = ?1 and us.markAsDelete = false ")      
	List<ClfOrderItems> getOpenOrderItems(String orderId);
	
//	@Query(value = "select itm.item_id , itm.order_id ,gct.type ,gcat.ads_type ,gcast.ads_sub_type ,gcs.scheme ,gcc.classified_category ,gcs2.classified_subcategory,gcl.language ,itm.clf_content,itm.created_ts, coir.total_amount,gce.edition_name,itm.ad_id,itm.category_group,itm.sub_group,itm.child_group,gg.classified_group,gsg.classified_sub_group,gcg.classified_child_group from clf_order_items itm inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_group gg on itm.category_group = gg.id inner join gd_classified_sub_group gsg on itm.sub_group = gsg.id inner join gd_classified_child_group gcg on itm.child_group = gcg.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type  = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_editions ce on ce.item_id = itm.item_id inner join gd_classified_editions gce on gce.id = ce.edition_id  where itm.order_id = ?1 and itm.mark_as_delete = false", nativeQuery = true)      
//	List<Object[]> getOpenOrderItemsDetailsByOrderId(String orderId);
	
//	@Query(value = "select itm.item_id , itm.order_id ,gct.type ,gcat.ads_type ,gcast.ads_sub_type ,gcs.scheme ,gcc.classified_category ,gcs2.classified_subcategory,gcl.language ,itm.clf_content,itm.created_ts, coir.total_amount,gce.edition_name,itm.ad_id from clf_order_items itm inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type  = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_editions ce on ce.item_id = itm.item_id inner join gd_classified_editions gce on gce.id = ce.edition_id  where itm.order_id = ?1 and itm.mark_as_delete = false", nativeQuery = true)      
//	List<Object[]> getOpenOrderItemsDetailsByOrderId(String orderId);
	
	@Query(value = "select itm.item_id , itm.order_id ,gct.type ,gcat.ads_type ,gcast.ads_sub_type ,gcs.scheme ,gcc.classified_category ,gcs2.classified_subcategory,gcl.language ,itm.clf_content,itm.created_ts, coir.total_amount,itm.ad_id from clf_order_items itm inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type  = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id inner join clf_order_item_rates coir on itm.item_id = coir.item_id  where itm.order_id = ?1 and itm.mark_as_delete = false", nativeQuery = true)      
	List<Object[]> getOpenOrderItemsDetailsByOrderId(String orderId);
	
//	@Query(value = "select uc.mobile_no, cpd.publish_date,itm.created_ts ,itm.category,gcc.classified_category,coir.total_amount,itm.status,cp.payment_status AS cp_payment_status,itm.download_status ,itm.clf_content,itm.item_id , itm.order_id,gcs2.classified_subcategory,ce.edition_id,gce.edition_name, co.payment_status AS co_payment_status from clf_order_items itm inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_orders co on co.order_id = itm.order_id left join clf_payments cp on cp.order_id = co.order_id inner join um_customers uc on co.customer_id = uc.customer_id inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type  = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join clf_publish_dates cpd on itm.item_id = cpd.item_id inner join gd_classified_languages gcl on itm.lang = gcl.id inner join  clf_editions ce on ce.item_id = itm.item_id inner join gd_classified_editions gce on gce.id = ce.edition_id  where itm.created_by = ?1 and itm.classified_type  = ?2  and itm.mark_As_Delete= false and cp.payment_status = 'COMPLETED'", nativeQuery = true)      
//	List<Object[]> getOpenOrderItemsDetails(Integer createdBy, Integer classifiedType);
	
	@Query(value = "select uc.mobile_no, itm.created_ts ,itm.category,gcc.classified_category,coir.total_amount,itm.status,cp.payment_status AS cp_payment_status,itm.download_status ,itm.clf_content,itm.item_id , itm.order_id,gcs2.classified_subcategory, co.payment_status AS co_payment_status, itm.scheme AS itm_scheme, gcs.scheme AS gcs_scheme from clf_order_items itm inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_orders co on co.order_id = itm.order_id left join clf_payments cp on cp.order_id = co.order_id inner join um_customers uc on co.customer_id = uc.customer_id inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type  = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id where itm.created_by = ?1 and itm.classified_type  = ?2  and itm.mark_As_Delete= false and cp.payment_status = 'COMPLETED'", nativeQuery = true)      
	List<Object[]> getOpenOrderItemsDetails(Integer createdBy, Integer classifiedType);
	
	@Query(value = "select uc.mobile_no, itm.created_ts ,itm.category,gcc.classified_category,coir.total_amount,itm.status,cp.payment_status AS cp_payment_status,itm.download_status ,itm.clf_content,itm.item_id , itm.order_id,gcs2.classified_subcategory, co.payment_status AS co_payment_status, itm.scheme AS itm_scheme, gcs.scheme AS gcs_scheme from clf_order_items itm inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_orders co on co.order_id = itm.order_id left join clf_payments cp on cp.order_id = co.order_id inner join um_customers uc on co.customer_id = uc.customer_id inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type  = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id where itm.classified_type  = ?1  and itm.mark_As_Delete= false and cp.payment_status = 'COMPLETED'", nativeQuery = true)      
	List<Object[]> getOpenOrderItemsDetailsByAdmin(Integer classifiedType);
	
	@Query(value = "select uc.mobile_no, itm.created_ts ,itm.category,gcc.classified_category,coir.total_amount,itm.status,cp.payment_status AS cp_payment_status,itm.download_status ,itm.clf_content,itm.item_id , itm.order_id,gcs2.classified_subcategory, co.payment_status AS co_payment_status, itm.scheme AS itm_scheme, gcs.scheme AS gcs_scheme from clf_order_items itm inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_orders co on co.order_id = itm.order_id left join clf_payments cp on cp.order_id = co.order_id inner join um_customers uc on co.customer_id = uc.customer_id inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type  = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id where co.customer_id = ?1 and itm.classified_type  = ?2  and itm.mark_As_Delete= false and cp.payment_status = 'COMPLETED'", nativeQuery = true)      
	List<Object[]> getOpenOrderItemsDetailsByCustomer(String customerId, Integer classifiedType);
	
//	@Query(value = "select status,count(*) from clf_order_items itm where itm.created_by = ?1 and mark_as_delete  = false group by status", nativeQuery = true)      
//	List<Object[]> getDashboardCountsByLogin(Integer userId);
	
//	@Query(value = "select status,count(*) from clf_order_items itm inner join clf_payment_response_tracking cp on itm.order_id = cp.sec_order_id inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_orders co on co.order_id = itm.order_id inner join um_customers uc on co.customer_id = uc.customer_id inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id where itm.created_by = ?1 and cp.payment_status = 'success' and itm.mark_as_delete  = false group by status", nativeQuery = true)      
//	List<Object[]> getDashboardCountsByLogin(Integer userId);
	
	@Query(value = "select status,count(*) from clf_order_items itm inner join clf_payment_response_tracking cp on itm.order_id = cp.sec_order_id inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_orders co on co.order_id = itm.order_id inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id where itm.created_by = ?1 and cp.payment_status = 'success' and co.order_type = 2 and itm.mark_as_delete  = false and co.booking_unit = ?2 group by status", nativeQuery = true)      
	List<Object[]> getDashboardCountsByLogin(Integer userId, Integer bookingUnit);
	
//	@Query(value = "select status,count(*) from clf_order_items itm inner join clf_payment_response_tracking cp on itm.order_id = cp.sec_order_id inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_orders co on co.order_id = itm.order_id inner join um_customers uc on co.customer_id = uc.customer_id inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id where cp.payment_status = 'success' and itm.mark_as_delete  = false group by status", nativeQuery = true)      
//	List<Object[]> getDashboardCountsByAdmin();
	
	@Query(value = "select status,count(*) from clf_order_items itm inner join clf_payment_response_tracking cp on itm.order_id = cp.sec_order_id inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_orders co on co.order_id = itm.order_id inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id where cp.payment_status = 'success' and co.order_type = 2 and itm.mark_as_delete  = false and co.booking_unit = ?1 group by status", nativeQuery = true)      
	List<Object[]> getDashboardCountsByAdmin(Integer bookingUnit);

	
//	@Query(value = "select status,count(*) from clf_order_items itm inner join clf_orders co on co.order_id = itm.order_id where co.customer_id = ?1 and itm.mark_as_delete  = false group by status ", nativeQuery = true)      
//	List<Object[]> getDashboardCountsByCustomerId(String customerId);
	
	@Query(value = "select status,count(*) from clf_order_items itm inner join clf_orders co on co.order_id = itm.order_id inner join clf_payment_response_tracking cp on itm.order_id = cp.sec_order_id where co.customer_id = ?1 and itm.mark_as_delete  = false and cp.payment_status = 'success' and co.order_type = 2 and co.booking_unit = ?2 group by status ", nativeQuery = true)      
	List<Object[]> getDashboardCountsByCustomerId(String customerId,Integer bookingUnit);
	
	@Query("from ClfOrderItems us where us.itemId = ?1 and us.markAsDelete = false ")      
	ClfOrderItems getItemDetailsOnItemId(String itemId);
	
//	@Query(value = "select itm.item_id, itm.order_id, itm.classified_type, itm.classified_ads_type, itm.scheme, itm.category, itm.subcategory, itm.lang, itm.clf_content, itm.created_by, itm.created_ts, coir.rate, coir.lines, coir.extra_line_rate, coir.line_count, coir.char_count, coir.total_amount, clo.customer_id, itm.classified_ads_sub_type,itm.ad_id,itm.category_group,itm.sub_group,itm.child_group from clf_order_items itm inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_orders clo on itm.order_id = clo.order_id where itm.item_id = ?1", nativeQuery = true)
//	List<Object[]> viewClfItemDetails(String itemId);
	
	@Query(value = "select itm.item_id, itm.order_id, itm.classified_type, itm.classified_ads_type, itm.scheme, itm.category, itm.subcategory, itm.lang, itm.clf_content, itm.created_by, itm.created_ts, coir.rate, coir.lines, coir.extra_line_rate, coir.line_count, coir.char_count, coir.total_amount, clo.customer_id, itm.classified_ads_sub_type,itm.ad_id, clo.booking_unit,clo.customer_name,clo.edition_type from clf_order_items itm inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_orders clo on itm.order_id = clo.order_id where itm.item_id = ?1", nativeQuery = true)
	List<Object[]> viewClfItemDetails(String itemId);
	
	@Query(value = "select itm.item_id , itm.order_id ,gct.type ,gcat.ads_type ,gcast.ads_sub_type ,gcs.scheme ,gcc.classified_category ,gcs2.classified_subcategory,gcl.language ,itm.clf_content,itm.created_ts, coir.total_amount,gce.edition_name from clf_order_items itm inner join gd_classified_types gct on itm.classified_type = gct.id inner join gd_classified_ads_types gcat on itm.classified_ads_type = gcat.id inner join gd_classified_ads_sub_types gcast on itm.classified_ads_sub_type  = gcast.id inner join gd_classified_schemes gcs on itm.scheme = gcs.id inner join gd_classified_category gcc on itm.category = gcc.id inner join gd_classified_subcategory gcs2 on itm.subcategory = gcs2.id inner join gd_classified_languages gcl on itm.lang = gcl.id inner join clf_order_item_rates coir on itm.item_id = coir.item_id inner join clf_editions ce on ce.item_id = itm.item_id inner join gd_classified_editions gce on gce.id = ce.edition_id  where itm.order_id = ?1 and itm.mark_as_delete = false", nativeQuery = true)      
	List<Object[]> getPendingCartItems(String orderId);
	
	@Query("from ClfOrderItems us where us.itemId in (?1) and us.markAsDelete = false ")      
	List<ClfOrderItems> getPenClfOnItmId(List<String> itemId);
	
	@Transactional
	@Modifying
	@Query(value = "UPDATE clf_order_items  SET status = ?1, changed_by = ?2, changed_ts = ?3 where item_id in (?4) and mark_as_delete = false", nativeQuery = true)      
	void updateClf(String status, Integer userId, Date changedTs, List<String> itemId);
	
	@Query(value = "select gcc.classified_category, coi.clf_content, coi.item_id, co.erp_order_id,coi.ad_id,coir.line_count from clf_order_items coi inner join clf_orders co ON coi.order_id = co.order_id inner join clf_publish_dates cpd on  cpd.item_id = coi.item_id inner join gd_classified_category gcc on gcc.id = coi.category inner join clf_order_item_rates coir on coi.item_id = coir.item_id where co.payment_status = 'APPROVED' and cpd.publish_date = ?1 and co.booking_unit = ?2 and cpd.download_status = false and cpd.mark_as_delete = false and coi.mark_as_delete = false", nativeQuery = true)
	List<Object[]> getAdsTobeDownload(Date date,Integer bookingUnit);
	
	@Query(value = "select uc.email_id,uc.mobile_no,coir.total_amount,bu.payment_child_id,coi.ad_id from clf_order_items coi inner join clf_orders co ON coi.order_id = co.order_id inner join um_customers uc on co.customer_id = uc.customer_id inner join clf_order_item_rates coir on coi.item_id = coir.item_id inner join booking_units bu on co.booking_unit = bu.booking_code where coi.item_id = ?1 and coi.mark_as_delete = false ", nativeQuery = true)
	List<Object[]> getOrderDetailsOnItemId(String itemId);
	
//	@Transactional
//	@Modifying
//	@Query(value = "UPDATE clf_order_items  SET download_status = true where item_id in (?1) ", nativeQuery = true)      
//	void updateDownloadConfirmStatus(List<String> itemIds);
	
}
